title: "Эфир Indexmod"
timezone: Europe/Moscow
description: A fashion and art chainpædia
cname: indexmod.xyz
url: 'https://indexmod.xyz'
baseurl: ''
defaults:
  - scope:
      path: ""
      type: "programs"
    values:
      permalink: ":title"
